### ISSUE TITLE
Run time error '75' Path/Access error

### ISSUE THREAD

**Issue by abpai** [finboxio/xlam#10]
A user couldn't get the add-on to work properly on Excel of Mac. Maybe related to Excel update to 16.18 for Mac.

![image](https://user-images.githubusercontent.com/4070686/48429845-8f666180-e733-11e8-8cc0-db11dfbcb57b.png)

![image](https://user-images.githubusercontent.com/4070686/48429859-94c3ac00-e733-11e8-89a9-87f842649b0d.png)

![image](https://user-images.githubusercontent.com/4070686/48429868-9d1be700-e733-11e8-8991-692a8b75fb53.png)

**Comment by bdentino** [comment]
@abpai was this a new installation or an update?

**Comment by abpai** [comment]
It was from a new installation.
