### ISSUE TITLE
Breaking Update: Microsoft Excel for Mac

### ISSUE THREAD

**Issue by abpai** [finboxio/xlam#8]
Excel add-in on Mac stopped after an auto-update of office.

Following dialog pops up on start up:
![image](https://user-images.githubusercontent.com/4070686/47580590-e0ddb680-d914-11e8-842f-c9c06d0196b9.png)

Debug leads to this:
![image](https://user-images.githubusercontent.com/4070686/47580608-ecc97880-d914-11e8-8664-4029997d2d7d.png)

Excel info is:
![image](https://user-images.githubusercontent.com/4070686/47580612-f0f59600-d914-11e8-8e15-47e92e8adb89.png)

**Comment by bdentino** [comment]
How did you get this license? I have a 'Retail License 2016' and it tells me there's no updates available past 16.16.3

**Comment by bdentino** [comment]
Fixed in #9
